#!/usr/bin/env bash
# This script transfers a file from a client to a server using scp

# Check if the correct number of parameters is provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extract parameters
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/

# Check if scp command was successful
if [ "$?" -eq 0 ]; then
    echo "File successfully transferred to $username@$server_ip:~/"
else
    echo "Error: File transfer failed."
fi
