#!/usr/bin/env bash
# This script configures Nginx to set up a 301 redirection

# Ensure Nginx is installed and running (if not already done)
sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start

# Create a backup of the default Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup

# Define the redirection in Nginx configuration
echo -e "\nlocation /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n" | sudo tee -a /etc/nginx/sites-available/default > /dev/null

# Restart Nginx to apply changes
sudo service nginx restart
