#!/usr/bin/env bash
# This script configures Nginx to set up a 301 redirection

apt-get update
apt-get -y install nginx
chmod o+w /var/www/html/
echo "Hello World!" > /var/www/html/index.html

# Backup default Nginx configuration
cp /etc/nginx/sites-enabled/default ~/defaultBackup

redirectLine="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://github.com;\n\t}"   
sed -i "s|server_name _;|${redirectLine}|" /etc/nginx/sites-enabled/default

service nginx restart
