#!/usr/bin/env bash
# Automatically installs and configures Nginx to listen on port 80
# Creates a file at the root of the server containing 'Hello World!'
# Redirects /redirect_me to https://github.com using sed

apt-get update
apt-get -y install nginx
chmod o+w /var/www/html/
echo "Hello World!" > /var/www/html/index.html

# Backup default Nginx configuration
cp /etc/nginx/sites-enabled/default ~/defaultBackup

redirectLine="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"   
sed -i "s|server_name _;|${redirectLine}|" /etc/nginx/sites-enabled/default

service nginx restart
