#!/usr/bin/env bash
# Automatically installs and configures Nginx

# Update package list
apt-get update

# Install Nginx
apt-get -y install nginx

# Allow write permissions to the HTML directory
chmod o+w /var/www/html/

# Create index.html with 'Hello World!'
echo "Hello World!" > /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Backup default Nginx configuration
cp /etc/nginx/sites-enabled/default ~/defaultBackup

# Configure redirection to https://github.com
redirectLine="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "s|listen 80 default_server;|${redirectLine}|" /etc/nginx/sites-enabled/default

# Configure custom 404 page
errorPage="server_name _;\n\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t\treturn 404 'Ceci n\'est pas une page\n';\n\t}"
sed -i "s|listen 80 default_server;|${errorPage}|" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
service nginx restart
