#!/usr/bin/env bash
# Update the package list

sudo apt-get update

# Install Nginx package
sudo apt-get install -y nginx

# Add custom HTTP response header to Nginx config
echo 'add_header X-Served-By "$HOSTNAME";' | sudo tee -a /etc/nginx/nginx.conf

# Restart Nginx service
sudo systemctl restart nginx
