#!/usr/bin/env bash
# This script displays listening ports that only shows listening sockets and
# shows the PID and name of the program to which each socket belongs.
# Display listening TCP ports with associated program information
if [ $# -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
