#!/usr/bin/env bash
# This script fixes Nginx to listen on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
echo " * nginx is not running"
kill "$(pgrep 'nginx' | head -1)"
