#!/usr/bin/env bash
# This script lists the content of the current directory, showing only part of the name

# Use a for loop to iterate through the files and directories
list=$(ls)

for i in $list; do
	echo "$i" | cut -d '-' -f2
done
