#!/usr/bin/env bash
# This script checks and provides information abut the school file

# Check if the file "school" exists
if [ -e "school" ]; then
	echo "school file exists"

	if [ -s "school" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	# check if the file is a regular file
	if [ -f "school" ]; then
		echo "school is a reqular file"
	fi
else
	echo "school file does not exist"
fi
