#!/usr/bin/env bash
# Check if the script is run with sudo
# Change the IP address resolution for localhost (127.0.0.2) and facebook.com(8.8.8.8.)
cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/etc/hosts
echo "8.8.8.8		facebook.com" >> ~/etc/hosts
cp -f ~/hosts.new /etc/hosts
