#!/usr/bin/env bash
# Use the 'ifconfig' command to ftech network interface information
# Then, use 'grep' to filter only the lines containing 'inet' (IPv4 addresses)
# Finally, use 'awk' to extract the IPv4 addresses from the filtered line
ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 6-
