#!/usr/bin/env bash
#Default server configuration
    location / {
        proxy_pass http://127.0.0.1:5003;
    }

    location /static/ {
        alias /path/to/your/AirBnB_clone_v4/web_dynamic/static/;
    }

    location /templates/ {
        alias /path/to/your/AirBnB_clone_v4/web_dynamic/templates/;
    }
